SELECT DISTINCT f.first_name
				,f.last_name
				,f.email--,
--				,ete.TYPE_NAME
--				,ete."TYPE"
--				,e.INTERNAL_ID
--				,fe.IS_ATTENDANCE 
FROM JUMP_WAREHOUSE.JUMP_SHARE.FAN_ENTITLEMENT fe
	LEFT JOIN JUMP_WAREHOUSE.JUMP_SHARE.EVENT e ON e.EVENT_ID = fe.EVENT_ID 
	LEFT JOIN JUMP_WAREHOUSE.JUMP_SHARE.FAN f ON f.FAN_ID = fe.FAN_ID 
	LEFT JOIN JUMP_WAREHOUSE.JUMP_SHARE.ORDER_ITEM oi ON oi.ORDER_ID = fe.ORDER_ID 
 			AND oi.EVENT_ID = fe.EVENT_ID 
 			AND oi.INVENTORY_ID = fe.INVENTORY_ID 
	LEFT JOIN JUMP_WAREHOUSE.JUMP_SHARE.ORDERS o ON oi.order_id = o.order_id 
	LEFT JOIN JUMP_WAREHOUSE.JUMP_SHARE.ENTITLEMENT_TRANSFER_ENTITLEMENT ete ON fe.FAN_ENTITLEMENT_ID = ete.ENTITLEMENT_ID
WHERE e.INTERNAL_ID IN ('TW260325','TW260328')
	AND oi.status = 'CONFIRMED'
	AND fe.IS_ATTENDANCE = 'True'
	AND oi.PRICE_CATEGORY_NAME NOT LIKE 'Vouchers'
	AND oi.PRICE_CATEGORY_NAME NOT LIKE 'Experience'
	and oi.ORGANIZATION_NAME = 'timberwolves'
	and fe.ORGANIZATION_NAME = 'timberwolves'
	AND f.email NOT LIKE '%@timberwolves.com%'
	AND f.email NOT LIKE '%@jump.com%'
ORDER BY email
